# Generated by Django 5.1.3 on 2024-11-27 21:06

import core.services.upload_photo_car
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(choices=[('BMW', 'Bmw'), ('AUDI', 'Audi'), ('Fiat', 'Fiat'), ('Mazda', 'Mazda'), ('Nissan', 'Nissan'), ('Scoda', 'Scoda'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('KIA', 'Kia'), ('Lexus', 'Lexus'), ('Mercedes-Benz', 'Mercedes Benz'), ('Mitsubishi', 'Mitsubishi'), ('Opel', 'Opel'), ('Peugeot', 'Peugeot'), ('Toyota', 'Toyota'), ('Volvo', 'Volvo'), ('Volkswagen', 'Volkswagen'), ('Other', 'Other')], max_length=50)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)])),
                ('car_model', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s]{2,49}$', 'min 2 max 50 symbols')])),
                ('information', models.CharField(max_length=350, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\s\\d]{2,349}$', 'first letter uppercase min 3 max 350')])),
                ('currency', models.CharField(choices=[('UAH', 'Uah'), ('USD', 'Usd'), ('EUR', 'Eur')], max_length=4)),
                ('region', models.CharField(choices=[('Kyiv', 'Kyiv'), ('Sevastopol', 'Sevastopol'), ('Avtonomna Respublika Krym', 'Avtonomna Respublika Krym'), ('Vinnytska', 'Vinnytska'), ('Volynska ', 'Volynska'), ('Dnipropetrovska', 'Dnipropetrovska'), ('Donetska', 'Donetska'), ('Zhytomyrskа', 'Zhytomyrskа'), ('Zakarpatska', 'Zakarpatska'), ('Zaporizka', 'Zaporizka'), ('Ivano-Frankivska', 'Ivano Frankivska'), ('Kyivska', 'Kyivska'), ('Kirovohradska', 'Kirovohradska'), ('Luhanska', 'Luhanska'), ('Lvivska', 'Lvivska'), ('Mykolaivska', 'Mykolaivska'), ('Odeska', 'Odeska'), ('Poltavska', 'Poltavska'), ('Rivnenska', 'Rivnenska'), ('Sumska', 'Sumska'), ('Ternopilska', 'Ternopilska'), ('Kharkivska', 'Kharkivska'), ('Khersonska', 'Khersonska'), ('Khmelnytska', 'Khmelnytska'), ('Cherkaska', 'Cherkaska'), ('Chernivetska', 'Chernivetska'), ('Chernihivska', 'Chernihivska')], max_length=25)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CarPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to=core.services.upload_photo_car.upload_photo_car, validators=[django.core.validators.FileExtensionValidator(['gif', 'jpeg', 'png'])])),
            ],
            options={
                'db_table': 'car_photos',
            },
        ),
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ccy', models.CharField(max_length=4)),
                ('buy', models.CharField(max_length=10)),
                ('sale', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
    ]
