# Generated by Django 5.0.6 on 2024-09-09 12:01

import core.services.upload_photo_car
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Crossover', 'Crossover'), ('Universal', 'Universal')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='model_car',
            field=models.CharField(default=1, max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\s]{2,49}$', 'first letter uppercase min 3 max 50')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='photo_car',
            field=models.ImageField(default=1, upload_to=core.services.upload_photo_car.upload_photo_car),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(choices=[('BMW', 'Bmw'), ('AUDI', 'Audi'), ('Fiat', 'Fiat'), ('Mazda', 'Mazda'), ('Nissan', 'Nissan'), ('Scoda', 'Scoda')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
