# Generated by Django 5.1.2 on 2024-10-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_model_car_carmodel_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Uah'), ('USD', 'Usd'), ('EUR', 'Eur')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
