# Generated by Django 5.1.2 on 2024-10-29 08:51

import core.services.upload_photo_car
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carmodel_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_model',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s]{2,49}$', 'min 2 max 50 symbols')]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='information',
            field=models.CharField(max_length=350, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\s\\d]{2,349}$', 'first letter uppercase min 3 max 350')]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='photo_car',
            field=models.ImageField(blank=True, upload_to=core.services.upload_photo_car.upload_photo_car, validators=[django.core.validators.FileExtensionValidator(['gif', 'jpeg', 'png'])]),
        ),
    ]
