# Generated by Django 5.1.2 on 2024-10-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carmodel_car_model_alter_carmodel_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=400)),
                ('information', models.CharField(max_length=350)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
    ]
