# Generated by Django 5.1.2 on 2024-10-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_currencymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencymodel',
            old_name='information',
            new_name='buy',
        ),
        migrations.RenameField(
            model_name='currencymodel',
            old_name='currency',
            new_name='ccy',
        ),
        migrations.AddField(
            model_name='currencymodel',
            name='sale',
            field=models.CharField(default='1', max_length=45),
            preserve_default=False,
        ),
    ]
