# Generated by Django 5.1.2 on 2024-11-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_carmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='region',
            field=models.CharField(choices=[('Kyiv', 'Kyiv'), ('Sevastopol', 'Sevastopol'), ('Avtonomna Respublika Krym', 'Avtonomna Respublika Krym'), ('Vinnytska', 'Vinnytska'), ('Volynska ', 'Volynska'), ('Dnipropetrovska', 'Dnipropetrovska'), ('Donetska', 'Donetska'), ('Zhytomyrskа', 'Zhytomyrskа'), ('Zakarpatska', 'Zakarpatska'), ('Zaporizka', 'Zaporizka'), ('Ivano-Frankivska', 'Ivano Frankivska'), ('Kyivska', 'Kyivska'), ('Kirovohradska', 'Kirovohradska'), ('Luhanska', 'Luhanska'), ('Lvivska', 'Lvivska'), ('Mykolaivska', 'Mykolaivska'), ('Odeska', 'Odeska'), ('Poltavska', 'Poltavska'), ('Rivnenska', 'Rivnenska'), ('Sumska', 'Sumska'), ('Ternopilska', 'Ternopilska'), ('Kharkivska', 'Kharkivska'), ('Khersonska', 'Khersonska'), ('Khmelnytska', 'Khmelnytska'), ('Cherkaska', 'Cherkaska'), ('Chernivetska', 'Chernivetska'), ('Chernihivska', 'Chernihivska')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
