# Generated by Django 5.1.3 on 2024-11-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_carmodel_photo_car_carphotomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencymodel',
            name='updated_at',
        ),
    ]
