# Generated by Django 5.1.2 on 2024-10-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usermodel_is_premium'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='users',
        ),
    ]
