# Generated by Django 5.1.2 on 2024-11-03 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usermodel_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='phone_number',
            field=models.CharField(default=38093, max_length=13, validators=[django.core.validators.RegexValidator('^(\\+38)(\\s|-)?(\\()?[0-9]{3}(\\))?(\\s|-)?([0-9]{3})(\\s|-)?([0-9]{2})(\\s|-)?([0-9]{2})$', 'Phone must start +380')]),
            preserve_default=False,
        ),
    ]
