# Generated by Django 5.1.3 on 2024-11-22 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0012_remove_currencymodel_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarViewingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_view', to='cars.carmodel')),
            ],
            options={
                'db_table': 'car_viewing',
            },
        ),
    ]
